import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Hunting Coder</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="keywords" content="Next.js, coders blog" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <Script src='/SC.js' strategy='lazyOnload'></Script> */}


        {/* <img className={styles.homeImg} src="/codehacker.jpg"/> */}
      </div>
      <main className={styles.main}>

        <h1 className={styles.title}>
          &lt;Hunting Coder/&gt;
        </h1>
        {/* <img className={styles.homeImg} src="/homeimg.jpg"/> */}
        <p className={styles.description}>
          Blog for Code Hunters, keep hunting
        </p>

        <div className={styles.myDiv}>
          <Link href="/blog" >
            <div className={styles.leftBtn}>
              <i>&lt;</i>
            </div>
            Latest Blogs
            <div className={styles.rightBtn}>
              <i>&gt;</i>
            </div>
          </Link></div>


      </main>

      {/* <footer className={styles.footer}> */}
      {/* </footer> */}
    </>

  )
}
